OSMfile: osmData/TX-To-TU.osm
buildConnFile: buildingConnection.csv
buildingConfigPath: config/tsukuba-tu-building-data.csv
jobsFile: config/jobs.csv
businessFile: config/business.csv
numberOfAgents: 3000
threadNumber: 10
infectedAgent: 10
vaccinationPercentage: 0.0
verbose: false
gridHeight: 10
gridWidth: 10
windowWidth: 800
windowHeight: 600
reportDir: report
reportInterval: 6
nr_step_size : 300
nr_day_to_simulate : 30
pathfindFileName: pathfind.csv 
lockdownMethod:
  name: reduceWorkhours
  activeCasesThreshold: 100
  businessWorkhours:
    restaurant:
      start: 11
      finish: 20
      workdays: [0,1,2,3,4,5,6]
    barbershop:
      start: 11
      finish: 20
      workdays: [0,1,2,3,4,5,6]
    
